# Proposal

## Research topic

## Data availability

During the process of identifying data sources, we wanted to ensure that the data was not aggregated, cleaning the data is manageable, and would be able to answer any business questions through visualizations.

Initially, we were highly interested in an Alzheimer's data set that appeared to be able to answer questions similar to "how does race affect the frequency Alzheimer's patients?", "does gender affect Alzheimer's?", and "are there specific regions in the country that have a higher number of cases of Alzheimer's?". Upon further investigation, we discovered that the data set structure was highly aggregated and the structure is very difficult to work with. The data was organized by each row corresponding to multiple stratifications. For example, one row corresponded to a specific question and the mean number of days for individuals that are Hispanic, female, and 50-64 years old. Overall, we determined the Alzheimer's data set to be fairly complex and would not be reasonable to structure it in a tidy, if at all possible, given the current structure and aggregations made. Therefore, we decided to change direction for our project and do a deeper dive into the current data structure and ensure its usability.

The National Oceanic and Atmospheric Administration (NOAA) gathers information on numerous stations across the United States to monitor tides and currents. The data is collected and recorded through sensors placed on each of the stations. Throughout the United States, sensors are recording water level (WLLW), air temperature, water temperature, barometric pressure, winds, relative humidity, and visibility. For our project, we will be specifically looking at the recorded water level for 6 different stations in different regions and states throughout the United States; the stations we will be analyzing are The Battery, NY; Virginia Key, Biscayne Bay, FL; Galveston Pier 21, TX; Monterey, CA; Prudhoe Bay, AK; and Honolulu, HI. For each station, predicted water levels are available for each time in 6-minute intervals, while verified water levels are done more sparingly. When changed to broader time intervals (such as monthly data), the data shows the highest tide, the Mean Higher High Water (MHHW), the Mean High Water (MHW), the Mean Sea Level (MSL), the Mean Tide Level (MTL), the Mean Low Water (MLW), the Mean Lower Low Water (MLLW), and the lowest tide. This data can easily be exported into a CSV file and can be exported with specified data ranges and time intervals, which we plan to utilize.

The current format of the data will be exported by the date, time (GMT), predicted water level (ft), preliminary water level (ft), and verified water level (ft). As each station is recorded separately, we will need to select the same parameters, time intervals, and data ranges for each station in separate CSV files, then merge all 6 station data sets into a single data set with an additional column to indicate the station location.
 


Link to all US stations: <https://tidesandcurrents.noaa.gov/map/>

Link to the 6 stations and station information used in analysis:

-   The Battery, New York: <https://tidesandcurrents.noaa.gov/stationhome.html?id=8518750>

-   Virginia Key, Biscayne Bay, Florida: <https://tidesandcurrents.noaa.gov/stationhome.html?id=8723214>

-   Galveston Pier 21, Texas: <https://tidesandcurrents.noaa.gov/stationhome.html?id=8771450>

-   Monterey, California: <https://tidesandcurrents.noaa.gov/stationhome.html?id=9413450>

-   Prudhoe Bay, Alaska: <https://tidesandcurrents.noaa.gov/stationhome.html?id=9497645>

-   Honolulu, Hawaii: <https://tidesandcurrents.noaa.gov/stationhome.html?id=1612340>
